import mongoose from "mongoose";

/**
 * Message Schema
 *
 * NEW FIELDS:
 *   isAI        – true when the message was generated by Chatty AI
 *   deletedFor  – array of userIds who "cleared" this chat.
 *                 If your userId is in this array, you won't see the message.
 *                 The other user is never affected (per-user soft delete).
 */
const messageSchema = new mongoose.Schema(
  {
    senderId: {
      type: mongoose.Schema.Types.ObjectId,
      ref: "User",
      required: true,
    },
    receiverId: {
      type: mongoose.Schema.Types.ObjectId,
      ref: "User",
      required: true,
    },
    text: {
      type: String,
      default: "",
    },
    image: {
      type: String,
      default: "",
    },
    file: {
      type: String,
      default: "",
    },
    fileName: {
      type: String,
      default: "",
    },

    // ── AI flag ─────────────────────────────────
    // true  → this message was written by Chatty AI
    // false → normal human message (default)
    isAI: {
      type: Boolean,
      default: false,
    },

    // ── Soft delete (per-user clear-chat) ────────
    // When a user clicks "Clear Chat", their userId is pushed here.
    // We filter messages on read: any message whose deletedFor array
    // contains the requesting user's id is excluded from results.
    deletedFor: [
      {
        type: mongoose.Schema.Types.ObjectId,
        ref: "User",
      },
    ],
  },
  { timestamps: true }
);

// Index for fast lookup of chat history between two users
messageSchema.index({ senderId: 1, receiverId: 1, createdAt: 1 });

const Message = mongoose.model("Message", messageSchema);

export default Message;
